@host = http://localhost:5229

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "Gerald",
    "lastname": "Ncube",    
    "password": "P4$$word!",
    "email": "gncube@gmail.com"
}
