@host = http://localhost:5229
@hostId = 354c0245-ecb3-43d6-8c8f-3c28e359de00
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VySWQgeyBWYWx1ZSA9IDM1NGMwMjQ1LWVjYjMtNDNkNi04YzhmLTNjMjhlMzU5ZGUwMCB9IiwiZ2l2ZW5fbmFtZSI6IkdlcmFsZCIsImZhbWlseV9uYW1lIjoiTmN1YmUiLCJqdGkiOiI5ODVhNjA1OC0yOWZlLTRhOGYtYWE1MC0xZGExMjkzYmIxZDMiLCJleHAiOjE3MDIxNTgxNzcsImlzcyI6IlBvdmhvRGlubmVyIiwiYXVkIjoiUG92aG9EaW5uZXIifQ.t8NUa89VAUjjVUtAJHyr3ycHA2Yl0_yXtNFvZFjv78c

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization:  Bearer {{token}}

    {
        "Name": "Seafood Menu",
        "Description": "A menu with seafood",
        "Sections": [
            {
                "Name": "Main Course",
                "Description": "Delicious seafood dishes",
                "Items": [
                    {
                        "Name": "Grilled Salmon",
                        "Description": "Salmon grilled to perfection"
                    },
                    {
                        "Name": "Shrimp Scampi",
                        "Description": "Shrimp cooked in garlic butter sauce"
                    }
                ]
            }
        ]
    }